### ISSUE TITLE
Reset zoom option

### ISSUE THREAD

**Issue by aodendaal** [nabeelvalley/EasyScrollVSCodeExtension#1]
Please can you add a Reset Editor Window Zoom option?

**Reset Zoom** in the View menu resets the whole editor but doesn't affect the code window, which your extension brilliantly does.

**Comment by nabeelvalley** [comment]
Hi, I've added this functionality as well as the ability control and reset both the Editor Window as well as the Workbench Zoom Levels in Version 0.1.0
