### ISSUE TITLE
Zoom doesn't work in .kt files

### ISSUE THREAD

**Issue by bobcat4848** [nabeelvalley/EasyScrollVSCodeExtension#3]
When I try to do the usual ctrl+scroll to zoom inside of a .kt file, it just doesn't work. If it's possible to fix this, that'd be amazing.

Thank you!

**Comment by nabeelvalley** [comment]
Hi @bobcat4848, sorry for the huge delay, totally missed issues in this repo

Unfortunately, the extension needs to set the option based on the VSCode Language ID. It doesn't look like Kotlin is in the list of supported Language ID's 

https://code.visualstudio.com/docs/languages/identifiers

If you are still using this though you can take a look at [the VSCode Docs](https://code.visualstudio.com/docs/editor/accessibility) for the built-in feature that does this now
