### ISSUE TITLE
could be possible to customize the shortcuts

### ISSUE THREAD

**Issue by charlitos85** [nabeelvalley/EasyScrollVSCodeExtension#4]
I very love the extention. I will like to have the possibility to customize the keyboard shortcuts.

**Comment by nabeelvalley** [comment]
Hi @charlitos85, this functionality is built into VSCode. Shortcuts can be updated using the Keyboard Shortcut menu and looking for: 

- `editor.action.fontZoomIn`
- `workbench.action.zoomIn`
- `editor.action.fontZoomOut`
- `workbench.action.zoomOut`
- `editor.action.fontZoomReset`
- `workbench.action.zoomReset`

You should be able to override the keyboard shortcut from there
