### ISSUE TITLE
Zoom scroll position works weird in new vscode version

### ISSUE THREAD

**Issue by Creta5164** [nabeelvalley/EasyScrollVSCodeExtension#5]
![weird zoom](https://user-images.githubusercontent.com/13521406/63210999-6a70a600-c12c-11e9-8d2d-532b8d176eb0.gif)  
The scroll position moves when zoom in and out.

### VSCode version  
Version : 1.37.1 (user setup)
Commit : f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date : 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362 (Windows 10 Pro - 1903)

**Comment by nabeelvalley** [comment]
Hi, the extension just activates some VSCode settings behind the scenes, this would likely be an issue with VSCode if you're still experiencing it, would make more sense to take it up [here](https://github.com/microsoft/vscode/issues)
